
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Splash from "./Splash";
import Navbar from "./Navbar/Navbar";
import HomePage from "./home/page";
import BackToTop from "./BackToTop";
import UpperNav from "./Navbar/upperNav";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Splash>
          {/* <UpperNav /> */}
          <Navbar  />
          {children}
          <BackToTop />
        </Splash>
      </body>
    </html>
  );
}
